In [1]:
import numpy as np

In [2]:
# !pip install numpy

In [3]:
# https://jalammar.github.io/visual-numpy/

In [4]:
my_list = [10,20,30,40]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

np.int64(40)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.random.random(5)

array([0.79118759, 0.63576116, 0.13518558, 0.20339534, 0.96493632])

In [13]:
# array aritmatic

In [14]:
my_list1 = [1,2]
my_list2 = [2,3]

In [15]:
my_list1 + my_list2

[1, 2, 2, 3]

In [16]:
my_numpy_array1 = np.array(my_list1)
my_numpy_array2 = np.array(my_list2)

In [17]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [18]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [19]:
my_numpy_array1 - my_numpy_array2

array([-1, -1])

In [20]:
my_numpy_array1 / my_numpy_array2

array([0.5       , 0.66666667])

In [21]:
my_numpy_array1 * 5

array([ 5, 10])

In [22]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [23]:
other_array = np.array([10,20,30,40,50])

In [24]:
other_array.min()

np.int64(10)

In [25]:
other_array.sum()

np.int64(150)

In [26]:
my_numpy_array1

array([1, 2])

In [27]:
other_array

array([10, 20, 30, 40, 50])

In [28]:
# arrange and indexing

In [29]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np_array = np.arange(0,10)

In [33]:
np_array[0]

np.int64(0)

In [34]:
np_array[-1]

np.int64(9)

In [35]:
np_array[1:4:]

array([1, 2, 3])

In [36]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [37]:
np_array[2:6:2]

array([2, 4])

In [38]:
# random

In [39]:
np.random.randn(4)

array([ 0.64778826,  0.37547238, -1.1684618 , -0.62510331])

In [40]:
np.random.randn(4,4)

array([[ 1.0762233 , -2.61072057,  0.3636351 , -0.01642833],
       [ 0.27930549, -0.72305264,  1.65022925, -0.59229912],
       [-1.38946967,  0.81705139,  0.95754856,  1.31559951],
       [-0.3967313 , -1.0236793 ,  1.27026197, -0.4092388 ]])

In [41]:
np.random.randint(1,300,5)

array([276,  40, 220, 241, 235], dtype=int32)