In [1]:
import numpy as np

In [2]:
my_matrix = [[5,10],[15,20]]

In [3]:
my_matrix

[[5, 10], [15, 20]]

In [4]:
my_matrix[0]

[5, 10]

In [5]:
my_matrix[1]

[15, 20]

In [6]:
my_matrix[0][1]

10

In [7]:
# row * column 

In [8]:
numpy_matrix = np.array([[5,10],[15,20]])

In [9]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [10]:
numpy_matrix.sum()

np.int64(50)

In [11]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.random.random((3,2))

array([[0.25091585, 0.12693216],
       [0.8977247 , 0.44873621],
       [0.90408281, 0.37625577]])

In [15]:
# matrix aritmetic

In [16]:
first_array = np.array([[10,20],[30,40]])
second_array = np.array([[5,15],[25,35]])

first_array + second_array

array([[15, 35],
       [55, 75]])

In [17]:
first_array = np.array((10,20,30,40))
second_array = np.array((5,15,25,35))

first_array + second_array

array([15, 35, 55, 75])

In [18]:
third_array = np.array([[50,60]])
third_array

array([[50, 60]])

In [19]:
first_array

array([10, 20, 30, 40])

In [20]:
fourth_array = np.array([
    [10,20,30,40,50]
])

In [21]:
# first_array + fourth_array

In [22]:
first_array * 2

array([20, 40, 60, 80])

In [23]:
first_array / 4

array([ 2.5,  5. ,  7.5, 10. ])

In [24]:
third_array = np.array([
    [10],[20]
])

third_array

array([[10],
       [20]])

In [25]:
third_array.shape

(2, 1)

In [26]:
first_array.shape

(4,)

In [27]:
first_array + third_array

array([[20, 30, 40, 50],
       [30, 40, 50, 60]])

In [28]:
third_array

array([[10],
       [20]])

In [29]:
first_array

array([10, 20, 30, 40])

In [30]:
# matrix multiplication

In [31]:
first_array

array([10, 20, 30, 40])

In [32]:
second_array

array([ 5, 15, 25, 35])

In [33]:
first_array * second_array

array([  50,  300,  750, 1400])

In [34]:
# dot product

In [35]:
first_matrix = np.array([
    [10,20,30]
])

first_matrix

array([[10, 20, 30]])

In [36]:
second_matrix = np.array([
    [2,3],[2,3],[2,3]
])

In [37]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [38]:
first_matrix.shape , second_matrix.shape

((1, 3), (3, 2))

In [39]:
result = first_matrix.dot(second_matrix)
result

array([[120, 180]])

In [40]:
result.shape

(1, 2)