In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([39, 75, 77, 26, 52, 70, 79, 86, 56, 70, 58, 81, 15, 31, 37, 93, 44,
       94, 71, 23], dtype=int32)

In [4]:
new_array > 25

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False])

In [5]:
new_array[new_array > 25]

array([39, 75, 77, 26, 52, 70, 79, 86, 56, 70, 58, 81, 31, 37, 93, 44, 94,
       71], dtype=int32)

In [6]:
new_array[new_array < 25]

array([15, 23], dtype=int32)

In [7]:
# transpose & reshape

In [8]:
matrix_array = np.array([
    [10,20],
    [20,30],
    [30,40]
])

matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [9]:
matrix_array.shape

(3, 2)

In [10]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [11]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [12]:
random_array = np.random.random((6,1))

In [13]:
random_array

array([[0.2212414 ],
       [0.86163355],
       [0.23434224],
       [0.93670287],
       [0.25709855],
       [0.66140212]])

In [14]:
random_array.shape

(6, 1)

In [15]:
random_array.reshape(3,2)

array([[0.2212414 , 0.86163355],
       [0.23434224, 0.93670287],
       [0.25709855, 0.66140212]])

In [16]:
# z-score

In [17]:
data = np.array([10,12,13,15,18,25,100,105])

In [18]:
# outlier

In [20]:
mean = np.mean(data)

In [21]:
mean

np.float64(37.25)

In [22]:
std = np.std(data)

In [23]:
std

np.float64(37.9333296719389)

In [24]:
z_scores =  (data - mean) / std

In [25]:
z_scores

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [58]:
import math

std_manuel = math.sqrt((
    (10-37.25) ** 2 
    + (12-37.25) ** 2 
    + (13-37.25) ** 2 
    + (15-37.25) ** 2 
    + (18-37.25) ** 2 
    + (25-37.25) ** 2 
    + (100-37.25) ** 2 
    + (105-37.25) ** 2
) / 8)

print(std_manuel)

37.9333296719389


In [59]:
z_scores[z_scores > 1]

array([1.65421809, 1.78602829])

In [60]:
data[z_scores > 1]

array([100, 105])

In [61]:
# math equations

In [62]:
# 2x + 3y = 8 and 5x +  7y = 19

In [63]:
# coefficent - x ve y'nin önündeki kat sayılar

In [65]:
A = np.array([
    [2,3],
    [5,7]
])

In [66]:
# constant - sabit sayılar

In [71]:
b = np.array([8,19])

In [72]:
solution = np.linalg.solve(A,b)

In [73]:
solution

array([1., 2.])